<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_BERLANGGANAN</name>
   <tag></tag>
   <elementGuidId>4d501317-912b-4aee-9cb4-a71c9294b872</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__layout']/div/div[2]/div/div/div/article/div[4]/div[4]/div[2]/div[2]/div[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://gerai.kompas.id/belanja/harian-kompas/kompas-digital-premium/?utm_source=kompasid&amp;utm_medium=produk2_paywall&amp;utm_campaign=konten_berbayar&amp;utm_content=https%3A%2F%2Fwww.kompas.id%2Fbaca%2Fopini%2F2021%2F01%2F14%2Fkrisis-lingkungan-dan-bencana-pandemi%2F</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gtm-paywall-berlangganan font-bold bg-green-lima border border-solid border-transparent rounded shadow-md cursor-pointer flex items-center justify-center text-white text-base font-normal h-9 hover:opacity-90 px-4 capitalize w-full leading-tight no-underline outline-none focus:outline-none</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            BERLANGGANAN
          </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__layout&quot;)/div[1]/div[@class=&quot;pt-12&quot;]/div[@class=&quot;mx-auto w-full max-w-xl&quot;]/div[1]/div[1]/article[@class=&quot;pt-10&quot;]/div[@class=&quot;relative z-999 w-full -mt-24&quot;]/div[@class=&quot;bg-white font-pt-sans w-full flex flex-col pb-8 lg:flex-row&quot;]/div[@class=&quot;flex flex-col px-4 w-full lg:order-none order-first&quot;]/div[@class=&quot;shadow-md flex flex-grow flex-col rounded-lg w-full bg-blue-royal-700 text-white&quot;]/div[@class=&quot;px-4 text-sm&quot;]/a[@class=&quot;gtm-paywall-berlangganan font-bold bg-green-lima border border-solid border-transparent rounded shadow-md cursor-pointer flex items-center justify-center text-white text-base font-normal h-9 hover:opacity-90 px-4 capitalize w-full leading-tight no-underline outline-none focus:outline-none&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__layout']/div/div[2]/div/div/div/article/div[4]/div[4]/div[2]/div[2]/div[4]/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'BERLANGGANAN')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='/Bulan'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 50.000'])[1]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='atau biarkan Google mengelola langganan Anda untuk paket ini:'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akses tak terbatas Kompas.id (web &amp; app)'])[2]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://gerai.kompas.id/belanja/harian-kompas/kompas-digital-premium/?utm_source=kompasid&amp;utm_medium=produk2_paywall&amp;utm_campaign=konten_berbayar&amp;utm_content=https%3A%2F%2Fwww.kompas.id%2Fbaca%2Fopini%2F2021%2F01%2F14%2Fkrisis-lingkungan-dan-bencana-pandemi%2F')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[4]/a</value>
   </webElementXpaths>
</WebElementEntity>
